
name: Clean migrate cabbage-tst

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle stuff
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Cache Gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: flywayInfo TST
        run: ./gradlew flywayInfo
        env:
          CABBAGE_TARGET_ENV: TST
          CABBAGE_DB_ID: ${{ secrets.CABBAGE_TST_DB_ID }}
          CABBAGE_DB_PASSWORD: ${{ secrets.CABBAGE_TST_DB_PASSWORD }}

