
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.1'

      - name: Cache Gradle stuff
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Cache Gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Show dir
        run: pwd

      - name: Show home structure
        run: ls -la ~


      - name: flyway clean-migrate CI
        run: ./gradlew :database:flywayClean :database:flywayMigrate :database:flywayInfo
        env:
          CABBAGE_TARGET_ENV: CI
          CABBAGE_DB_PASSWORD: ${{ secrets.CABBAGE_CI_DB_PASSWORD }}

      - name: build app
        run: ./gradlew :app:buildApp


      - name: Show home structure
        run: ls -la ~

      - name: Show gradle structure
        run: ls -la ~/.gradle

